CONTRACTOWNER: smurfalexp24
WALLETPASSWORD: PW5KCH1kz3L1WZDCy98Hrr8kur73T6KfFGHfLzYPb2bAVG4pHR5ns
JUNGLEENDPOINT: http://jungle2.cryptolions.io:80
ACCOUNTSGENERATOR: ricardojmv53
ACCOUNTSGENERATORPASSWORD: EOS6YeWnZDHYgtHDvTuqq5NDW3kiCKSoKZQLv8BhppSMjM3uLuoRR
HOST: 0.0.0.0
PORT: 5000
TOKEN: UF
