CONTRACTOWNER: smurfalexp24
WALLETPASSWORD: PW5JgLRGuzXmZPKT27vq155hFnLWb1vkt5Ahci5idHaqmYKWVC78G
JUNGLEENDPOINT: http://jungle2.cryptolions.io:80
ACCOUNTSGENERATOR: ricardojmv53
ACCOUNTSGENERATORPASSWORD: EOS6YeWnZDHYgtHDvTuqq5NDW3kiCKSoKZQLv8BhppSMjM3uLuoRR
HOST: 0.0.0.0
PORT: 5000
