ACCOUNTSGENERATOR: ricardojmv53
ACCOUNTSGENERATORPASSWORD: EOS6YeWnZDHYgtHDvTuqq5NDW3kiCKSoKZQLv8BhppSMjM3uLuoRR
CONTRACTOWNER: smurfalexp24
HOST: 0.0.0.0
JUNGLEENDPOINT: http://jungle2.cryptolions.io:80
PORT: 5000
TOKEN: HBD
WALLETPASSWORD: PW5KCH1kz3L1WZDCy98Hrr8kur73T6KfFGHfLzYPb2bAVG4pHR5ns
